name: quiz_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^4.0.2
  intl: ^0.16.1

  ## アニメーション用
  flutter_sequence_animation: ^3.0.1

  ## List操作が簡単
  quiver: ^2.0.5

  ## bloc用
  equatable: ^1.0.0
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0

  ## FirebaseのDBやストレージ
  firebase_storage: ^3.1.1
  firebase_core: ^0.4.0+1
  cloud_firestore: ^0.11.0+2

  ## 認証系
  firebase_auth: ^0.15.3+1
  google_sign_in: ^4.1.1
  flutter_twitter_login: ^1.1.0

  ## Toast表示
  fluttertoast: ^3.1.3

  ## プログレスダイアログ表示
  progress_dialog: ^1.2.0

  ## 全画面プログレス表示
  flutter_progress_hud: ^1.0.2

  ## 画像選択Picker
  image_picker: ^0.6.3+1

  ## 追加のアイコン
  eva_icons_flutter: ^2.0.0

  ## agora
  agora_rtc_engine: 1.0.5
  permission_handler: ^3.0.0

  ## 音声 to テキスト
  flutter_speech: ^1.1.0

  # Tabbar
  tab_indicator_styler: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/empty_user_image.png
  fonts:
    - family: MyFlutterIcons
      fonts:
        - asset: assets/fonts/MyFlutterIcons.ttf
